#! /bin/sh

function completed() {
	#type man strftime to see full list of date formatting options.
	CURRENT_DATE=$(date "+%a %d %b %Y")
	CURRENT_TIME=$(date "+%H:%M:%S")
	echo "-----------------------------------------------------------------------------"
	echo "Build Complete at $CURRENT_TIME on $CURRENT_DATE."
	echo "-----------------------------------------------------------------------------"
	echo
}

tools/apache-ant-1.8.2/bin/ant -logger org.apache.tools.ant.NoBannerLogger -buildfile ops/build/build.xml $@

EXIT_CODE=$?

completed

exit $EXIT_CODE

