<div class="entry">
    <div class="label">Name</div>
    <div class="value" id="$label$Name" >$caregiver.name$</div>
</div>
<div class="entry">
    <div class="label">Education</div>
    <div class="value" id="$label$Education">$caregiver.education$</div>
</div>
<div class="entry">
    <div class="label">Contact</div>
    <div class="value" id="$label$Contact">$caregiver.contact$</div>
</div>
<div class="entry">
    <div class="label">Occupation</div>
    <div class="value" id="$label$Occupation">$caregiver.occupation$</div>
</div>
<div class="entry">
    <div class="label">Marital Status</div>
    <div class="value" id="$label$MaritalStatus">$caregiver.maritalStatus$</div>
</div>
