<div>
    <div class="page" class="listTable">
        <table class="listTable">
            <thead class="header">
            <tr>
                <td>Priority</td>
                <td>Item</td>
                <td>Cost</td>
            </tr>
            </thead>
            <tbody>

            $needs:{
                <tr>
                    <td>$it.priority$</td>
                    <td>$it.item$</td>
                    <td>$it.cost$</td>
                </tr>
            }$

            </tbody>
        </table>
    </div>

</div>



