ALTER TABLE Student ADD COLUMN STUDENT_ID varchar(255)
;
ALTER TABLE Student ADD COLUMN SEX varchar(255)
;
ALTER TABLE Student ADD COLUMN DATE_OF_BIRTH varchar(255)
;
ALTER TABLE Student ADD COLUMN STUDENT_CLASS varchar(255)
;