ALTER TABLE Student ADD COLUMN STUDENT_ID varchar(255)
;
ALTER TABLE Student ADD COLUMN SEX varchar(255)
;
ALTER TABLE Student ADD COLUMN DATE_OF_BIRTH varchar(255)
;
ALTER TABLE Student ADD COLUMN STUDENT_CLASS varchar(255)
;
ALTER TABLE Student ADD COLUMN STUDENT_DISCIPLINARY varchar(1000)
;
ALTER TABLE Student ADD COLUMN STUDENT_PERFORMANCE varchar(1000)
;
ALTER TABLE Student ADD COLUMN STUDENT_PROFILE int
;