CREATE TABLE Event (
event_id int generated by default as identity (start with 1) primary key,
event_title varchar(150),
event_date date,
event_time time,
event_venue varchar(400),
event_coordinator varchar(150),
event_description varchar(1000),
event_notes varchar(1000)
);