CREATE TABLE Notes (
	STUDENT_ID int foreign key references STUDENT(id),
    NOTE_ID int generated by default as identity (start with 1),
    NOTE varchar(1000),
    NOTE_DATE TIMESTAMP,
	primary key (STUDENT_ID,NOTE_ID)
);




