<div id="subscriberList">
    <div class="page">

     <table border="0">
            <thead class="header">
                    <tr>
                    <td>Name</td>
                    <td>Email</td>
                    </tr>
            </thead>
             $viewsubscribers:{
                <tr>
                    <td>$it.subscriberName</td>
                    <td>$it.subscriberEmail$</td>
                </tr>
            }$
      </table>
     </div>
</div>