<div id="eventListPages">
    <div class="page" class="listTable">
        <table class="listTable">
            <thead class="header">
            <tr>
                <td>Event</td>
                <td>Date Of Event</td>

            </tr>
            </thead>
            <tbody>

            $events:{
                <tr class="event">
                    <td class="name"><a href="/events/$it.id$">$it.title$</a></td>
                    <td class="date">$it.date$</td>
                </tr>
            }$

            </tbody>
        </table>
    </div>

</div>



