<div id="eventListPages">
    <div class="page">
        <table>
            <thead class="header">
            <tr>
                <td>Event</td>
                <td>Date Of Event</td>

            </tr>
            </thead>
            <tbody>


            <tr class="event">
                <td class="name"><a href="/events/$it.eventId$">Sports Day</a></td>
                <td class="date">12/03/2011</td>

            </tr>
            <tr class="event">
                <td class="name"><a href="/events/$it.eventId$">Annual Day</a></td>
                <td class="date">15/03/2011</td>

            </tr>
            </tbody>
        </table>
    </div>

</div>



