DELETE FROM PUBLIC.EVENTATTENDEES;
DELETE FROM PUBLIC.STUDENT_NOTE;
DELETE FROM PUBLIC.STUDENT_TALENT;
DELETE FROM PUBLIC.STUDENT;
DELETE FROM PUBLIC.TALENT;
DELETE FROM PUBLIC.NOTE;
DELETE FROM PUBLIC.EVENT;
