INSERT INTO "PUBLIC"."STUDENT"
( "ID", "NAME", "RELIGION", "CASTE", "SUB_CASTE", "AREA" ,"STUDENT_ID", "DATE_OF_BIRTH")
VALUES (1 , 'Bob1', 'Hindu', 'Brahmin', 'Brahmin', 'Uttar Pradesh','12345', CURRENT_TIMESTAMP)
INSERT INTO "PUBLIC"."STUDENT"
( "ID", "NAME", "RELIGION", "CASTE", "SUB_CASTE", "AREA" ,"STUDENT_ID", "DATE_OF_BIRTH")
VALUES (2 , 'Bob2', 'Hindu', 'Brahmin', 'Brahmin', 'Uttar Pradesh','34545', CURRENT_TIMESTAMP)
INSERT INTO "PUBLIC"."STUDENT"
( "ID", "NAME", "RELIGION", "CASTE", "SUB_CASTE", "AREA" ,"STUDENT_ID", "DATE_OF_BIRTH")
VALUES (3 , 'Bob3', 'Hindu', 'Brahmin', 'Brahmin', 'Uttar Pradesh','64262',CURRENT_TIMESTAMP)
INSERT INTO "PUBLIC"."STUDENT"
( "ID", "NAME", "RELIGION", "CASTE", "SUB_CASTE", "AREA" ,"STUDENT_ID", "DATE_OF_BIRTH")
VALUES (4 , 'Bob4', 'Hindu', 'Brahmin', 'Brahmin', 'Uttar Pradesh','16346', CURRENT_TIMESTAMP)
INSERT INTO "PUBLIC"."STUDENT"
( "ID", "NAME", "RELIGION", "CASTE", "SUB_CASTE", "AREA" ,"STUDENT_ID", "DATE_OF_BIRTH")
VALUES (5 , 'Bob5', 'Hindu', 'Brahmin', 'Brahmin', 'Uttar Pradesh','83415', CURRENT_TIMESTAMP)
INSERT INTO "PUBLIC"."STUDENT"
( "ID", "NAME", "RELIGION", "CASTE", "SUB_CASTE", "AREA" ,"STUDENT_ID", "DATE_OF_BIRTH")
VALUES (6 , 'Bob6', 'Hindu', 'Brahmin', 'Brahmin', 'Uttar Pradesh','23462', CURRENT_TIMESTAMP)
INSERT INTO "PUBLIC"."STUDENT"
( "ID", "NAME", "RELIGION", "CASTE", "SUB_CASTE", "AREA" ,"STUDENT_ID", "DATE_OF_BIRTH")
VALUES (7 , 'Bob7', 'Hindu', 'Brahmin', 'Brahmin', 'Uttar Pradesh','35734', CURRENT_TIMESTAMP)

INSERT INTO "PUBLIC"."TALENT"  VALUES ( 1, 'Sports' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 2, 'Humanities' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 3, 'Dancing' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 4, 'Debate' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 5, 'Singing' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 6, 'Drama' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 7, 'Quiz' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 8, 'Science Club' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 9, 'Creative Writing' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 10, 'Musical Instrument' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 11, 'Story Writing' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 12, 'Choir' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 13, 'Art' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 14, 'Drawing' );
INSERT INTO "PUBLIC"."TALENT"  VALUES ( 15, 'Craft' );;

INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (1,1);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (1,13);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (3,2);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (3,5);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (4,1);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (5,1);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (6,2);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (6,3);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (6,12);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (6,13);
INSERT INTO "PUBLIC"."STUDENT_TALENT" VALUES (7,6);
