<html>
<body>

<table>
    <tr style="text-align:left;">
        <th>Name</th>
        <th>Religion</th>
        <th>Caste</th>
        <th>Sub Caste</th>
        <th>Area</th>
    </tr>
    <tbody>

    $students:{
    <tr>
        <td>$it.name$</td>
        <td>$it.religion$</td>
        <td>$it.caste$</td>
        <td>$it.subCaste$</td>
        <td>$it.area$</td>
    </tr>
    }$

    </tbody>
</table>

</body>
</html>
