<div class="informationMessage">
    <p>You are about to move ALL the students up one class.</p>
    <p>This means that for example, students in class LKG will move up to UKG.</p>
</div>
<div class='lastUpdate'>
      <p>The records were last updated on: ---- </p>
</div>

<div class="buttonBar">
    <form action="/admin/annualupdate" method="POST">
        <input type="submit" name="submit" value="Update students" />
    </form>
</div>