<form id="sendendofsponsorship" name="sendendofsponsorship" action="/admin/endofsponsorshipmailsentPage" method="post" >
    <label for="to">To:</label>
    <input type="text" id="to" name="to" />
    <label for="subject">Subject:</label>
    <input type="text" id="subject" name="subject" />
    <br/><br/>
    <label for="comments">Comments:</label>
    <br/>
    <textarea name="comments" id="comments" rows="5" cols="30">Thanks for sponsoring.</textarea>
    <div><input type="submit" id="send" name="send" value="Send" /></div>
</form>