<form id="sendnewsletter" name="sendnewsletter" action="." method="get" >
    <table>
        <tr>
            <td>
                <span>To:</span>
            </td>
            <td>
                 <input type="text" id="to" name="to" />
            </td>
        </tr>
        <tr>
            <td>
                <span>Subject:</span>
            </td>
            <td>
                 <input type="text" id="subject" name="subject" />
            </td>
        </tr>
        <tr>
            <td>
                <span>Comments:</span>
            </td>
            <td>
                <textarea name="comments" id="comments" rows="5" cols="30"></textarea>
            </td>
        </tr>
    </table>
    <div><input type="button" id="attach" name="attach" value="Attach" /></div>
</form>