<div id="talentInfo">
    <form>
        <div class="updateEntry">
            <div class="label">Talent Description<span class="mandatory">*</span></div>
            <div class="textSpace">
                <input type="text" name="description" id="description" value="" class="updateValue"></input>
            </div>
        </div>

        <div id="update">
            <input type="submit" id="register" value="Add Talent"/>
        </div>
    </form>
</div>