<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<title>$title$</title>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
	<script type="text/javascript" src="/scripts/studentSearch.js"></script>
	<script type="text/javascript" src="/scripts/recordEvent.js"></script>
    <link rel="stylesheet" type="text/css" href="/styles/styles.css">
</head>
<body>

<div id="page">
<div id="header">
$header()$
</div>

<div id="columns">

<div id="sidebar">
$sidebar()$
</div>

<div id="body">
$body$
</div>
<br class="clear">
</div>
</div>

</body>
</html>