<html>
<head>
	<title>Student Search</title>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
	<script type="text/javascript" src="/scripts/studentSearch.js"></script>
	<script type="text/javascript" src="/scripts/recordEvent.js"></script>
    <link rel="stylesheet" type="text/css" href="/styles/styles.css">
</head>
<body>

<div id="page">
<div id="header">
$header()$
</div>

<div id="sidebar">
$sidebar()$
</div>

<div id="body">
$body$
</div>
</div>

</body>
</html>