
      <div class="sideBarHeader">Search </div>
	
	  <div class="sideBarContent">
	  <li>
	  <p class="indent">
	  <a href="/students/search">Search Students</a></p>
	  </li>
	  </div>
      
      <br/>
	  
	  <div class="sideBarHeader">
      Student Records
      <br/>
      </div>
      
      <div class="sideBarContent">
      <li>
          <p class="indent"><a href="/students">View All</a>
      </p>
      </li>
      
      <li>
      <form method="post" action="/students/promote">
       <input type="submit" value="Annual Class Update"/>
      </form>
      </li>

      </div>
       
	  <br/>

	  <div class="sideBarHeader">
      Events
      </div>
      
      <div class="sideBarContent">
      
      <li>
      <p class="indent">
      <a href="/events">
      View Events
      </a>
      </p>
      </li>
        
      <li>
      <p class="indent">
      <a href="/events/create">
      Record Event
      </a>
      </p>
      </li>
       
      </div>
        
       
