<div class="sideBarHeader">Search </div>
<div class="sideBarContent">
    <ul>
        <li>
            <p class="indent">
                <a id="studentSearch" href="/students/search">Search Students</a>
            </p>
        </li>
        <li>
            <p class="indent">
                <a id="studentSearchBySponsor" href="/students/searchbysponsor">Search Students by Sponsor</a>
            </p>
        </li>
    </ul>
</div>

<br/>

<div class="sideBarHeader">Student Records</div>
<div class="sideBarContent">
    <ul>
        <li>
            <p class="indent">
                <a id="viewStudents" href="/students">View Students</a>
            </p>
        </li>
        <li>
            <p class="indent">
                <a id="addNewStudent" href="/students/create">Add New Student</a>
            </p>
        </li>
    </ul>
</div>

<br/>

<div class="sideBarHeader"> Events </div>
<div class="sideBarContent">
    <ul>
        <li>
            <p class="indent">
                <a id="viewEvents" href="/events"> View Events </a>
            </p>
        </li>
        <li>
            <p class="indent">
                <a id="createAnEvent" href="/events/create"> Create an Event </a>
            </p>
        </li>
    </ul>
</div>

<br/>

<div class="sideBarHeader"> Admin </div>
<div class="sideBarContent">
    <ul>
        <li>
            <p class="indent">
                <a id="admin" href="/admin"> Tools </a>
            </p>
        </li>
        <li>
             <p class="indent">
                 <a href="/admin/monthlyreports?sponsored=Yes"> Monthly Reports </a>
             </p>
        </li>
        <li>
             <p class="indent">
                 <a href="/admin/sendnewsletter"> Send Newsletter </a>
             </p>
        </li>
    </ul>
</div>

<br/>

<div class="sideBarHeader">Needs</div>
<div class="sideBarContent">
    <ul>
        <li>
            <p class="indent">
                <a id="bigNeeds" href="/bigneeds">Big Needs</a>
            </p>
        </li>
    </ul>
</div>

