      <a href="/sukrupa/app/students/search">Search</a><br/>

      <a href="/404">Student Records</a><br/>
        <a href="/sukrupa/app/students">View Student Records</a><br/>
        <a href="/404">Import</a><br/>
        <a href="/404">Update</a><br/>

      <a href="/404">Events</a><br/>
        <a href="/404">View Events</a><br/>
        <a href="/sukrupa/app/events/record">Record Event</a><br/>
